name: Despliegue continuio

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js version
        uses: actions/setup-node@v6
        with:
          node-version: 18
      - name: Build
        working-directory: ./hangman-api
        run: |
          npm ci
          npm run build --if-present
      - name: Upload dist folder
        uses: actions/upload-artifact@v7
        with:
          name: build-code
          path: hangman-api/dist

  delivery:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Download artifact 
        uses: actions/download-artifact@v8
        with:
          name: build-code
          path: hangman-api/dist
      - name: Build docker image
        working-directory: ./hangman-api
        run: docker build reyesgrinformatica/hangman-api -f Dockerfile.workflow .

